# Set the build language to Python
language: python

#Set the python version to 3.6
python:
  - "3.6"

install:
  - pip install -r requirements.txt

# Run the unit test
script:
  - python3 fichierTest.py